

services:
  medicalapi:
    container_name: medicinemanagement
    build:
      context: .
      dockerfile: Process/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MYSQL_HOST=mysql
   
  mysql:
    container_name: mysql
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: medicinedb
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
